### PR TITLE
Update traduction  fr.json

### PR DESCRIPTION
**Pull request by trint30**
fix typo

### CODE REVIEW

**Comment by farhatahmad** [comment]
Hi,

Thank you for taking the time to update theses translations.

We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/

**Comment by trint30** [comment]
Hi,

Your welcome.

I'm afraid your link point to a 404.

**Comment by farhatahmad** [comment]
(sorry about that) fixed now

**Comment by trint30** [comment]
Ok, I make the patch.

**Pull request closed without merging**
