### PR TITLE
Enabled StandardError global rescue to production only.

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
+ Fixed some failing tests.

## Testing Steps

> 1. Pull the code.
> 2. Install the dependencies `bundle install && npm|yarn install`.
> 3. Clean the previous assets build by running `rm app/assets/builds/*` (This won't remove .keep since it's hidden).
> 4. Clean the database and tmp files for a better isolation by running `rails tmp:clear && rails db:schema:cache:clear && rails db:drop && rails db:create && rails db:migrate:with_data`
> 5. Run the linter and specs `bundle exec rubocop --parallel && bundle exec rspec && npx eslint app/javascript/* --ext .jsx,.js`
> 6. Run `./bin/dev` to run the assets builders processes and the Puma server all at once.

### CODE REVIEW

**Comment by hadicheaito1** [comment]
@KH-Amir-TN Changes look good, but Sonar cloud changes need to be made

**Comment by KH-Amir-TN** [comment]
> @KH-Amir-TN Changes look good, but Sonar cloud changes need to be made

Yup, I think it's better if who wrote the duplicated tests fix it.
I may brake things because I'm not fully aware of those functionalities details.

**Comment by farhatahmad** [comment]
I'm going to vote against making this change. Having code that behaves differently in production will likely only cause headaches in the future. We may want to look at other solutions to this problem

**Comment by KH-Amir-TN** [comment]
> I'm going to vote against making this change. Having code that behaves differently in production will likely only cause headaches in the future. We may want to look at other solutions to this problem

Makes sense,

**Pull request closed without merging**
