### PR TITLE
UI/UX: Added `ErrorBoundary` component.

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
## Description

https://reactjs.org/docs/error-boundaries.html
Usage:
```
{// Top level, boundary will will display TopErrorPage in place to avoid bubbling the error and having the whole tree unmouted}
<ErrorBoundary fallback={TopErrorPage}>
  <ErrorBoundary>
      {// By default, with no fallback UI any encountered error will unmount the subtree}
     <NavBar />
   </ErrorBoundary>
  <Container>
    <ErrorBoundary fallback={MainErrorPage}>
      {// When encountering an error the error boundary will display MainErrorPage in place}
        <Outlet />
    </ErrorBoundary>
  </Container>
    <ErrorBoundary>
      <Footer/>
  </ ErrorBoundary>
<ErrorBoundary />
````
A deep level usage:
````
export default function AdminPanel(){
return (
   <Container>
  <SideBar />
   <Content>
      {// E.g we want to if possible catch an error bubbling inisde the admin panel tab content area before it ruins the entire UI}
     <ErrorBoundary fallback={PanelErrorPage}>
         <Table />
         {...}
     </ErrorBoundary>
   </Content>
</Container>
);
}
````
Props:
- fallback: A react component that will be rendered in place of the subtree in case of an encountered error, the component will have two props `error` and `errorInfo`, the first is the error object and the latter is a react errorInfo object that includes information about the error from react's perspective e.g the component stack trace.
## Testing Steps

> 1. Pull the code.
> 2. Install the dependencies `bundle install && npm|yarn install`.
> 3. Clean the previous assets build by running `rm app/assets/builds/*` (This won't remove .keep since it's hidden).
> 4. Clean the database and tmp files for a better isolation by running `rails tmp:clear && rails db:schema:cache:clear && rails db:drop && rails db:create && rails db:migrate:with_data`
> 5. Run the linter and specs `bundle exec rubocop --parallel && bundle exec rspec && npx eslint app/javascript/* --ext .jsx,.js`
> 6. Run `./bin/dev` to run the assets builders processes and the Puma server all at once.

### CODE REVIEW

**Comment by scouillard** [comment]
Where are we planning to use this?

**Review by scouillard — APPROVED** [review]

**Review by hadicheaito1 — APPROVED** [review]
I see the use of this. But where do we plan on using this as Samuel asked? Everywhere? And what does the usage look like when using this component in another file?

**Comment by KH-Amir-TN** [comment]
> Where are we planning to use this? We can see a live example [here](https://codepen.io/gaearon/pen/wqvxGa?editors=0010)

Wherever we require catching a raising exception during rendering, stop its bubbling and make side effects preserving the rest of the UI intact (mounted),
Example, we may like to display some UI inside our adminpanel content area if something goes wrong there instead of affecting the entire UI by counting on a higher error boundary in the tree,
I'm quoting this from the official docs: _"For example, Facebook Messenger wraps content of the sidebar, the info panel, the conversation log, and the message input into separate error boundaries. If some component in one of these UI areas crashes, the rest of them remain interactive."_
So, for our case I think we'd start by one top level error boundary and maybe another one that try catching errors in the main container subtree trying to keep hold of the layout in case of an issue.
And as we go will see the need to add other boundaries,

**Comment by farhatahmad** [comment]
Why are we using a class component? Shouldn't we use a function component for consistency?

**Pull request merged**
