### PR TITLE
Color room state for better overview

### PR DESCRIPTION
**Pull request by Dennis1993**
Bring colors to the state of a room for better overview.

Before:
image

After:
image

### CODE REVIEW

**Comment by farhatahmad** [comment]
Thanks for this PR - can you run this command for linting? `eslint app/javascript/* --ext .js,.jsx --fix`

**Comment by Dennis1993** [comment]
Thanks for your answer!
I use github.com online in the web. I can't run it here I think. Sorry.

**Comment by farhatahmad** [comment]
No worries - I will do it from my end

**Comment by Dennis1993** [comment]
Thank you very much! :)

**Pull request merged**
