### PR TITLE
Room owner option: authentication is required to join a room

### PR DESCRIPTION
**Pull request by ucb-ck**
##
117446677-b553d200-af3c-11eb-8ce2-569b6b3080e0
117446675-b4bb3b80-af3c-11eb-89c0-f5e4122b7c4f

Description

Added a new room option which allows room owners to configure if authentication is required before a specific room can be joined. Clarified german translation to reflect distinction between settings for all rooms of a gl instance and single rooms.

Organization - Site Settings - Settings - Require Authentication for Rooms
enabled: options in room settings and global room configuration disappear
disabled: option in room settings is configurable (see below)

Organization - Room Configuration - Require authentication before joining
enabled: has the same effect as setting "Require Authentication for Rooms" to enabled
optional: room owners are able to configure this setting
disabled: room owners are not able to configure this setting, disabled for all rooms

##Testing Steps

add require-authentication-to-join to ROOM_FEATURES in .env
restart greenlight

### CODE REVIEW

**Comment by ucb-ck** [comment]
Addresses Issue #1714 

feature request: 'Allow only logged in users' in Room settings

**Comment by jgribonvald** [comment]
@ffdixon

**Comment by jgribonvald** [comment]
A usefull feature working well ! I've tested it and it's work well, I merged it on the last greenligth version and it's working well, will go on production with it next week.

@ucb-ck I've made a Pull request on your repo/branch to provide the French translation.

I hope my comment will help to merge this usefull feature !

**Comment by GhaziTriki** [comment]
@farhatahmad Could you please take a closer look and see if you can merge it?

**Comment by beckerr-rzht** [comment]
Is there a chance that this feature will be merged soon?

**Pull request closed without merging**
