### PR TITLE
Remove Sign Up button when using OIDC

### PR DESCRIPTION
**Pull request by jdr00t**
Solves Part 1 of #5062
Sign Up button is not needed when using OpenID Connect

### CODE REVIEW

**Comment by antobinary** [comment]
Thank you for sending us a CLA too!

**Comment by farhatahmad** [comment]
Funny story - Greenlight v2 used to do this (maybe 3 years ago) and then people complained that users didn't understand that `Sign in` and `Sign up` for external accounts was the same thing - leading to confusion (ie "where is the signup button")

Hence, the `Sign up` button was added to solve this issue

**Comment by Ithanil** [comment]
@jdr00t Suggestion: Remove the Sign-Up Button also from the RequireAuthentication card in app/javascript/components/rooms/room/join/RequireAuthentication.jsx

**Review by farhatahmad — APPROVED** [review]

**Comment by farhatahmad** [comment]
closes #5517

**Pull request merged**
