### PR TITLE
policy Link in Cookie Banner

### LINKED ISSUE #2595: Cookie Banner covers legal notice and privacy policy
The current solution of placing the cookie banner is legally problematic, as it covers the references/links to the legal notice and privacy policy on most systems.
At least in germany the law/legal interpretation states that the legal notice has always to be easily found and available on a website. If the cookie banner covers it this isn't fulfilled any more.

Since the cookie banner isn't really legally necessary in germany (see also issue #1628 for more information) the current solution seems to bring real harm without gaining a much of benefit for german admins.

It would be great if the cookie banner would be repositioned in order to prevent legal problems for german bbb-providers and -admins.

### PR DESCRIPTION
**Pull request by mrkeksi**
## Description
Added Policy Link in Cookie Banner. 
Will close #2595

## Testing Steps
Delete Cookies -> Cookie Banner will pop up

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by farhatahmad** [comment]
Should we be showing Legal in the cookie banner? I'm leaning towards just adding something like "For more information, please see our privacy policy" (where privacy policy is a link)

**Comment by mrkeksi** [comment]
I have already seen every constelation. I would leave the banner as thin as possible. That way we can also just link to the privacy policy with "more information". Would that be ok?

**Comment by farhatahmad** [comment]
Hi,

To help us better test and review community PRs, we have now implemented a **mandatory** PR template. We would really appreciate it if you were to update the description of this PR to match the template below. 

For more information, please see: https://github.com/bigbluebutton/greenlight#source-code--contributing

The template must be in the following format (it is automatically applied to all new PRs):
```
<!--- 
IMPORTANT
This template is mandatory for all Pull Requests.
Please follow the template to ensure your Pull Request is reviewed.
-->

<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Testing Steps
<!--- Please describe in detail how to test your changes. -->

## Screenshots (if appropriate):
<!--- Please include screenshots of ALL visual changes. -->

```

**Comment by farhatahmad** [comment]
I've went with a slightly different approach here: https://github.com/bigbluebutton/greenlight/pull/2647

**Pull request closed without merging**
