### PR TITLE
add customizable Links to Imprint and Privacy Policy

### PR DESCRIPTION
**Pull request by einhirn**
I added two items in "site settings" as suggested in #1268.
When you put an URL in there it gets added as imprint or privacy policy link, respectively, in the page footer. If left empty, it doesn't display.

Let's see what rubocop says 😁

### CODE REVIEW

**Comment by Sea444** [comment]
I don't understand Travis CI check. It fails because we change privacy policy? Yes, that's waht the pull request is about. So everything is ok?

**Comment by einhirn** [comment]
An automated test failed. I added the specification for the test by copy&paste, so I don't know yet why the one for imprint went through and the one for privacy policy didn't. I'll check and double check...

**Comment by einhirn** [comment]
Yep. Changing "privacy policy url" and checking whether the change is reflected in "imprint url" won't work. Travis was right...

**Comment by mabras** [comment]
I do not thinks you should add the `de_DE.yml` text. this will be overwritten from Transifex service. Maybe just English. I am not sure though.

**Comment by robbi5** [comment]
Thanks for the PR. Could we change »Imprint« to something like »Legal«? Imprint is an often used wrong translation: http://s521972252.online.de/wiki/index.php?title=Impressum_-_getting_it_right

**Comment by Sea444** [comment]
Yeah, I looked at the english version of a german website for translation... :-D

Ok, so "Legal" and "Privacy policy" would be correct. Like on apple.com:

grafik

**Comment by einhirn** [comment]
Thanks @robbi5 for pointing that out!

Starting with the least important part, I renamed the branch, hoping it would be reflected here. Nope, it wasn't. So #1421 replaces this PR.

**Pull request closed without merging**
