### PR TITLE
Add basic anti-spam measures to the registration form

### PR DESCRIPTION
**Pull request by hng**
**Problem**
The registration form can be used to send spam. See #2093 

**Solution**
As using Google reCaptcha is not an option for everyone and it‘s not enabled by default I've added basic anti-spam measures with this PR:
- validate the name field to not include an http(s) url
- added honeypot captcha with invisible_captcha gem to the registration form

Solves #2093

### CODE REVIEW

**Comment by farhatahmad** [comment]
Thanks for creating the issue and submitting the PR to fix it. Can you split the name validation code and the honeypot captcha into 2 separate PRs please?

**Comment by hng** [comment]
Yes I am going to do that

**Comment by farhatahmad** [comment]
Going to close this then. Will be waiting for the split PR. Thank you :)

**Comment by hng** [comment]
@farhatahmad Done, see #2114 and #2115

**Pull request closed without merging**
