### PR TITLE
Adds OpenID Connect.

### PR DESCRIPTION
**Pull request by mapidentity**
Dear BigBlueButton,

Thank you for creating and maintaining Greenlight! This pull request contains an implementation for OpenID Connect  support. We required it because we do not use LDAP but do manage our own users (through Keycloak). Apparently we are not alone here, see also issue #1151. Perhaps this PR will be closed mercilessly per this comment: https://github.com/bigbluebutton/greenlight/issues/1151#issuecomment-607435319, although we do hope you might reconsider.

~~known caveat: OAUTH2_REDIRECT must be set to avoid invalid redirect_uri from Keycloak.~~

**Edit:**
Google and Microsoft specific provider dependencies have been removed. Configurations for most popular social logins have been added. Help with further testing is desired.

### CODE REVIEW

**Comment by farhatahmad** [comment]
"Mercilessly" is not how I would describe how the other issue was closed. As I explained there, merging in these implementations means we agree to support them. With the multiple methods we already support, as well as configurable SMTP settings, there is already too many issues for us to handle. Adding in 2 authentication methods will make it so that we can't properly support the project and that's not something that I think is correct. 

I will point others who ask to this PR so they can implement it for their own deployments, but we're just not able to support it and therefore will not merge it. We appreciate you sending the PR as it will definitely help others who are looking for this authentication method.

**Comment by lmm-git** [comment]
This decision is very sad as more and more universities and schools are using ODIC. for example, our university uses it and it will be very difficult for us to run the system without this feature. Even more, Office 365 and Google is using more or less the same protocol, so it is not a completely new method.

Just saying that everyone can just pull the changes from here is not sufficient as well, because in future there will be merge conflicts meaning most people will not be able to use this functionality.

Bascially, for us this feature is a blocker for using the project at our school/university.

**Comment by mapidentity** [comment]
@farhatahmad thank you for reviewing this PR. Your position is very understandable. This solves an immediate problem for us, but as @lmm-git points out keeping in sync with releases will be problematic. We would be willing to invest some time in adjusting this PR (incl. docs) so it works for Google and Office365 as well (removing those specific dependencies, they all seems to do the same thing). However we do not want to waste anyones time - your answer is very clear.

**Comment by jfederico** [comment]
Let's take a look to this again.

Almost a year go I worked on some specific implementation for OpenID as well, but we never merged. While Office365 and Google are the more used authentication methods in education, the Open standards bring us more value. We are all about openess.

Just to be clear, I am not saying we are going to merge it as it is, nor that we are going to do it right away. But I am re-opening it so we keep close track of this.

@mapidentity if you want to give it a shot please go ahead. I am all ears.

What we would be looking at is to have something more generic. As you pointed out, ideally we would make it work with OpenID, Google, and Microsoft at the very least.

**Comment by weeman1337** [comment]
Hey, is there anything we can do bringing this one forward? Could we help updating documentation etc.? I'm very interested in having OpenIdConnect support, but Google / M$ is a no-go.

**Comment by moschlar** [comment]
I tried testing this and I get 
`ERROR: [868acc8a-70b8-4fe7-bfb0-be767c691ef3] (openid_connect) Authentication failure! invalid_credentials: Rack::OAuth2::Client::Error, invalid_client `
Can somebody figure out why that would happen?

**Comment by mapidentity** [comment]
Dear maintainers (@farhatahmad , @jfederico), please have a look at the additions to this PR. Is this implementation in the desired direction you would like to go?

**Comment by mapidentity** [comment]
Kind reminder, @jfederico any thoughts on this yet?

**Comment by bssher** [comment]
@mapidentity did you figure out how to configure keycloak and greenlight? We are in the same boat.

**Comment by weeman1337** [comment]
> @mapidentity did you figure out how to configure keycloak and greenlight?

I configured that successfully: Basically you can look up all the endpoints you need here `https://{{ YOUR KEYCLOAK HOST }}/auth/realms/master/.well-known/openid-configuration`.

Additionally I added an open id client with a secret and a mapping for the username like this:
image

**Comment by bssher** [comment]
@mapidentity thank you!

**Comment by bssher** [comment]
In the .env file below what variables did you set for  using keycloak and pointing to the right keycloak client?

Google Login Provider (optional)
#
# For in-depth steps on setting up a Google Login Provider, see:
#
#   https://docs.bigbluebutton.org/greenlight/gl-config.html#google-oauth2
#
# The GOOGLE_OAUTH2_HD variable is used to limit sign-ins to a particular set of Google Apps hosted
# domains. This can be a string with separating commas such as, 'domain.com, example.com' or
# a string that specifies a single domain restriction such as, 'domain.com'.
# If left blank, GreenLight will allow sign-in from all Google Apps hosted domains.
GOOGLE_OAUTH2_ID=
GOOGLE_OAUTH2_SECRET=
GOOGLE_OAUTH2_HD=

# Twitter Login Provider (optional)
#
# Twitter Authentication is deprecated and will be phased out in a future release.

# Microsoft Office365 Login Provider (optional)
#
# For in-depth steps on setting up a Office 365 Login Provider, see:
#
#   https://docs.bigbluebutton.org/greenlight/gl-config.html#office365-oauth2
#
OFFICE365_KEY=
OFFICE365_SECRET=
OFFICE365_HD=

# OAUTH2_REDIRECT allows you to specify the redirect_url passed to oauth on sign in.
# It is useful for cases when Greenlight is deployed behind a Network Load Balancer or proxy
OAUTH2_REDIRECT=

**Comment by weeman1337** [comment]
@bssher have a look at the change set. It includes some new lines in the env file:

```
# OpenID Connect Provider (optional)
#
# For in-depth steps on setting up a OpenID Connect Login Provider, see:
#
#   https://docs.bigbluebutton.org/greenlight/gl-config.html#openid-connect
#
OPENID_CONNECT_CLIENT_ID=
OPENID_CONNECT_CLIENT_SECRET=
OPENID_CONNECT_ISSUER=
OPENID_CONNECT_SITE=
OPENID_CONNECT_DISCOVERY=
OPENID_CONNECT_UID_FIELD=
OPENID_CONNECT_AUTHORIZATION_ENDPOINT=
OPENID_CONNECT_TOKEN_ENDPOINT=
OPENID_CONNECT_END_SESSION_ENDPOINT=
OPENID_CONNECT_HD=
```

**Comment by DoktorAerzt** [comment]
I have a problem with adding this. I get an
```
 OpenIDConnect::Discovery::DiscoveryFailed (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)):
```
error. 

But i added my CA to the container. 

i used
```
COPY ./ssl/CA.crt /root/

RUN cp /root/*.crt /usr/local/share/ca-certificates/ \
        && /usr/sbin/update-ca-certificates
```

to add it and verifyed it with 
```
curl --verbose https://Server-withcert.org 
```

But everythink i tryed. Greenlight wont use me CA

**Comment by beatrubi** [comment]
Successfully attached Greenlight to the [Univention UCS](https://www.univention.de/produkte/ucs/) [OpenID Connect Adapter](https://www.univention.de/produkte/univention-app-center/app-katalog/openid-connect-provider/). Due to the lack of documentation, I had to dig into the sources to bring the stuff to life, so I'd like to share my receipt.

My steps:
* [Install Greenlight](https://docs.bigbluebutton.org/greenlight/gl-install.html), test, test, test
* [Rebuild Greenlight](https://docs.bigbluebutton.org/greenlight/gl-customize.html) from [the the forked repo](https://github.com/mapidentity/greenlight/tree/openid-connect)
```
mv greenlight greenlight.old
git clone https://github.com/mapidentity/greenlight.git
cd greenlight
git checkout openid-connect
cp ../greenlight.old/.env .
cp ../greenlight.old/docker-compose.yml .
cp -r ../greenlight.old/log .
cp -r ../greenlight.old/db .
./scripts/image_build.sh adfinissygroup/greenlight release-v2
$EDITOR .env
$EDITOR docker-compose.yml
```
* Created an OIDC client in UCS LDAP, subtree Univention, oidc, object type *OpenID Connect relying party service*
  * Redirect URI `https://bbb.example.com/b/auth/openid_connect/callback`
* Configure Greenlight
```
OPENID_CONNECT_CLIENT_ID=<client id from LDAP object>
OPENID_CONNECT_CLIENT_SECRET=<client secret from LDAO object>
OPENID_CONNECT_ISSUER=https://ucs-sso.example.com
```
There is no need to add further variables.

**Comment by dlecan** [comment]
This feature is very important for me, it would allow simple SSO for my users.
Thank you

**Comment by jfederico** [comment]
Closing this issue in favour of #1399

**Comment by ThomasAppDev** [comment]
> I have a problem with adding this. I get an
> 
> ```
>  OpenIDConnect::Discovery::DiscoveryFailed (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)):
> ```
> 
> error.
> 
> But i added my CA to the container.
> 
> i used
> 
> ```
> COPY ./ssl/CA.crt /root/
> 
> RUN cp /root/*.crt /usr/local/share/ca-certificates/ \
>         && /usr/sbin/update-ca-certificates
> ```
> 
> to add it and verifyed it with
> 
> ```
> curl --verbose https://Server-withcert.org 
> ```
> 
> But everythink i tryed. Greenlight wont use me CA
> 
> Also wget only works when i update it
> 
> ```
> apk --update add wget
> ```

Did you find an solution? I am struggling with the same problem

**Comment by flyinghuman** [comment]
just want to let you know that the OpenID Connect Documentation Part ist missing on Website: 

https://docs.bigbluebutton.org/greenlight/gl-config.html#openid-connect

**Pull request closed without merging**
