### PR TITLE
Added SAML2 support

### PR DESCRIPTION
**Pull request by phavekes**
#180

### CODE REVIEW

**Comment by jfederico** [comment]
Hi @phavekes,
First of all, thanks for the PR. I know it has been a while, but we are trying to catch up with projects.

Can you please condensate all your code in one commit and update the Gemfile?

I'll check it out as soon as you do those updates

**Comment by foobarable** [comment]
Is there any chance, that this MR would make it in the current master? It would help us a lot in our setup

**Comment by farhatahmad** [comment]
Hi @foobarable,

We ran into tons of issues with SAML after we implemented it, so it was removed.

You're free to pull this PR into you're own deployment if you want

**Comment by foobarable** [comment]
Uh, thats sad to hear. Then we may not want to head that way. What kind of problems were those? Maybe we could be of any help with those?

**Comment by foobarable** [comment]
Are other omniAuth strategies more likely to be merged into master? What about OpenID? (I could open an issue for that, if it's more fitting to discuss this someplace else)

**Comment by hex-m** [comment]
There is a post about OIDC (OpenID Connect) in #569 

> We actually have this in place in another repo.

I guess he is refering to [this](https://github.com/bigbluebutton/omniauth-bbbltibroker) which is not very active.

I vote for a dedicated issue to discuss this. :)

**Pull request merged**
