### PR TITLE
SIP support with static PIN for each room

### LINKED ISSUE #1412: Ability to set static voicebridge PIN per conference / conference room in greenlight
see [#8371](https://github.com/bigbluebutton/bigbluebutton/issues/8371) in bigbluebutton issue section.

It should be possible to start a conference with static voicebridge PIN by bbb API: https://bbb.EXAMPLE.tld/bigbluebutton/api/create?name=EXAMPLE&meetingID=EXAMPLE&attendeePW=EXAMPLE&moderatorPW=EXAMPLE&voiceBridge=EXAMPLE&checksum=EXAMPLE

But it is not possible to set a static PIN in greenlight. 

The option to set a static voicebridge PIN which is automatically identical with conference room code would be even better.

The ability to set a static voicebridge PIN is important for conference invitations (so that you can tell the PIN before the day of the conference).

Kind regards

### PR DESCRIPTION
**Pull request by tisoft**
Create a static PIN for each room, to be able to send the SIP dial in data to participants before the meeting is started.

## Description

The SIP PIN is generated from the room name, so it stays the same, even if the sessions is closed. The feature is only enabled, if the voice bridge phone number is set. If it is not set, the current behavior of generating a new SIP PIN for each new session is kept.

## Testing Steps

1. set the `VOICE_BRIDGE_PHONE_NUMBER` environment variable to your SIP telephone number. This value will be displayed in each room.
2. setup the BBB SIP Integration, if you use Scalelite, you can follow the instructions from https://github.com/MBcom/bbb-clustersip.git to setup a central SIP gateway for your BBB cluster
3. Greenlight will generate automatically a static conference PIN for each room and shows it next to the telephone number

## Screenshots (if appropriate):

image

This PR is an extraction of https://github.com/MBcom/enforce-authentication-greenlight from @MBcom.

Fixes #1412, #1572, #1645

### CODE REVIEW

**Comment by farhatahmad** [comment]
Thank you for submitting this PR. Go to mark is an `on hold` until Scalelite natively supports SIP

**Comment by ThomasAppDev** [comment]
We would love to take advantage of the change. Is it already foreseeable if and when it will be merged?

**Comment by ThomasAppDev** [comment]
> Thank you for submitting this PR. Go to mark is an `on hold` until Scalelite natively supports SIP

As the changes also work completly without scalelite, is it necessary to wait until scalelite to support SIP?

**Comment by ThomasAppDev** [comment]
Will the feature be available in Greenlightv2 or v3? Can we already deploy it at our system and when will it be in the official release?

Thank you!

**Comment by farhatahmad** [comment]
This won't be merged into v2, as there will only be security updates to v2. v3 will implement something similar to this in a future release

**Pull request closed without merging**
