### PR TITLE
GRN2-xx: Small changes/improvements to the recording settings

### PR DESCRIPTION
**Pull request by farhatahmad**
Changes:
  - Improved wording of strings
  - Small code quality changes
  - Removed "Active Session" warning

The reason I removed the warning is that I believe it is partially misleading/inaccurate. The warning appears if the session is running and the room owner attempts to change a setting. My issue with it is that the room setting should still be changeable even if the meeting is running, even if the change won't apply until the meeting ends and a new one is created. This is how the rest of the room settings work, so making 1 of them work differently than the others could cause some confusion

What I would rather do is maybe provide a more general warning for all settings and not just the recording setting if the room is running, but I believe that can be branched off to a different PR

### CODE REVIEW

**Comment by ichdasich** [comment]
Hm, i think the active session warning had a point to be there, i.e., to prevent funny expectations of users when they change a setting during a session. Furthermore (if like me) you pull the setting to display a dedicated consent form, starting a session with recordings enabled, and then changing it during the session, might break that (i.e.: Disclaimer not displayed even though the session is being recorded)

**Comment by farhatahmad** [comment]
@ichdasich Sorry was still updating the description with my reasoning. The setting can still be changed, but it'll only apply once the room is ended and a new one is created (just like the other settings)

**Comment by ichdasich** [comment]
Hm, so, depends on when it is written to the GL pg; If that happens immediately, my point applies. Otherwise you would have to keep state somewhere, no?

**Comment by matiasilva** [comment]
Another comment I have which I'm not sure if this was touched by the changes here is the "This session is recorded" red text when the user joins. In the PR it was sandwiched between the room name and "You have been asked to join".

**Comment by ichdasich** [comment]
Wasn't that taken out anyway?

**Comment by mrkeksi** [comment]
I think he's trying to tell us that the clue looks too bruised?

image

Whats about a banner?
image
I don't know if it could be implemented that quickly

**Comment by farhatahmad** [comment]
Yeah I'm not a huge fan of the red warning. Maybe something like this would be a better match? 

image

**Comment by matiasilva** [comment]
I like this but with the color differences it's hard to associate the banner with the red join and the banner can somewhat easily go unread. Perhaps some explanatory text below the join button? Not sure.

**Comment by farhatahmad** [comment]
The red join is only due to that being my local Primary Colour. I'd like to avoid too much "intrusion" or else some one will inevitably ask to make that message configurable as well

**Comment by mrkeksi** [comment]
Because blue is not a alerting colour and it’s the most used Color in Greenlight whats about yellow? Alert-warning is More visibility to users then the standard one

**Comment by yanosz** [comment]
Thanks for picking this up and mergint the PR. A few thought's on this PR 

* Having and adequate notice when joining rooms is afair the most debated effect of #1296. I still find it very hard to reach a consensus. IMHO customization very likely to happen; it could help to simpliy customization  w.r.t to all variants proposed here, instead of trying to find a common ground (e.g. have an input-Field in the admin-settings support html-input?).
* Personally, I placed the join notice right beside the invitation, because I think, that the user's actions referes to both. Users are invited to join a room with recording present. Unfornuatly, the default warning colors ("yellow") is quite light, thus hard to read. That's why the text is red. Due to its privacy implications, it's worth to have the user's attention. I don't like the idea of having banner, since the visual distance does not refelect the semantic closeness.
* The refactorings (naming, etc.) appear to be minor, but I'd hesitate to refactor, before having a suitable test coverage. Afair there's almost no coverage for joiner.rb and the JSON / Rails API. I'd be helpful to have a test checking the correctness of each refactoring in this commit.

**Comment by farhatahmad** [comment]
So we've decided to approach this in a slightly different way. By default, everything will continue to work as before. Rooms will be created and recorded without the required consent from the joiners.

I've added a Site Setting called "Require Room Owner and Joiner Consent to Recording". If set to enabled, it displays the option in the Room Configuration tab which then displays it in the Create/Update Room Modal. 

I've also changed the room joiner message to require an explicit checkbox click to confirm that they agree/consent to their info potentially being recorded. (Still trying to find the right wording for the message)

The reason it was done this way, is so that the default behaviour isn't changed for everyone, and it allows each site admin to specify whether they want this feature or not.

**Comment by ichdasich** [comment]
I like the sollution.

**Comment by yanosz** [comment]
Sounds reasonable .... my master thesis is due in about two weeks. Hence I've no time for checking the sources.

**Comment by ichdasich** [comment]
Good luck! If you want an independent kind-of-does-it-for-a-living review, let me know.

**Comment by mrkeksi** [comment]
what about people who have shared rooms they don't get a hint. do you mean the phrase recording_present that does not appeal yet? I find it briefly and succinctly formulated.

**Comment by farhatahmad** [comment]
@yanosz No worries. Best of luck!

**Comment by defnull** [comment]
Is there a reason why there are two settings now? `config.require_consent_default` can only be set via site-settings (not via environment variables), and there is a `recording` flag for `config.room_features` which *can* be changed via `ROOM_FEATURES` environment variable. The second option has no effect as long as the first is not true. I'm unsure where the difference is.

**Pull request merged**
