### PR TITLE
Review Admin Panel 

### PR DESCRIPTION
**Pull request by volga629**
Please review code for new feature admin panel for greenlight

### CODE REVIEW

**Comment by jfederico** [comment]
Hi @volga629 thanks for the PR.
One thing I can see before even starting a review is that your PR is not passing even travis. You need to run rubocop and rspec to make sure nothing is broken. We can start from there.

Also, can you publish a few screen caps so we can start discussing the UI?

**Comment by techverx** [comment]
last login detail
uer listing
screenshot from 2019-02-28 18-32-54
screenshot from 2019-02-28 18-35-08

**Comment by volga629** [comment]
We submitted screenshots can please help resolve all the code conflicts.

**Comment by ffdixon** [comment]
> We submitted screenshots can you please help resolve all the code conflicts.

Thanks again for sharing this.

Scrutinizer gives direct links to each of the offending code along with a description of the warning.

Do you still have access to the developer available who worked on the original changes?

**Comment by volga629** [comment]
Based on details duplication was not introduced by our code 


 ```
 introduced 5 months ago by
Joshua Arts
```

**Comment by volga629** [comment]
I am trying just understand what dev need to take a look

**Comment by jfederico** [comment]
Thanks again for the PR, but we are not going to use your implementation.

We are working right now on an update that will cover user management but also organization settings while this is aligned with the styling we have in Greenlight. You should see an update in master in the next days that hopefully it covers your use case too.

**Comment by volga629** [comment]
the team was working on adjustments to meet all requirements

**Comment by ffdixon** [comment]
@volga629 We've actually gone ahead and implemented our own administration interface that you'll see shortly in Green Light.  Your team can see the work here

  https://github.com/bigbluebutton/greenlight/tree/admin-panel

Feedback welcome!

**Pull request closed without merging**
