### PR TITLE
fix: health_check SMTP check when no auth required

### PR DESCRIPTION
**Pull request by jgribonvald**
The health_check controller implemented for the SMTP check try to authenticate in all case even when no auth is set and required.

### CODE REVIEW

**Review by farhatahmad — APPROVED** [review]

**Comment by farhatahmad** [comment]
@jgribonvald Can you rebase this to master please?

**Comment by jgribonvald** [comment]
@farhatahmad done

**Comment by lonesomewalker** [comment]
Seems to be still an issue :-/
Have SMTP server which requires no auth because whitelisted IP.
Unfortunately no "forgot password link" is shown -> no emails can be sent.

**Comment by jgribonvald** [comment]
@lonesomewalker I'm not on the latest version so I can't check, but this is working well at least on 2.9.2 version when you set only the domain param, other properties should not be set.

**Pull request merged**
