### PR TITLE
Add validation for email field on invitations

### LINKED ISSUE #2463: Invitation email field is not validated to be an email address
The email field from the invite user modal is not validated to actually be an email address. 

This can cause UX problems when typing in a bad formatted email address, it can also cause privacy problems as everything that is typed into the email field is saved and can be displayed on the "invited" tab.

### PR DESCRIPTION
**Pull request by hng**
Fixes #2463:

The email field from the invite user modal is not validated to actually be an email address.

This can cause UX problems when typing in a bad formatted email address, it can also cause privacy problems as everything that is typed into the email field is saved and can be displayed on the "invited" tab.

### CODE REVIEW

**Comment by farhatahmad** [comment]
Haven't had a chance to test this yet, but wouldn't it prevent an admin from sending multiple invitations (by `,` separating them)?

**Comment by hng** [comment]
> Haven't had a chance to test this yet, but wouldn't it prevent an admin from sending multiple invitations (by `,` separating them)?

This PR also works with multiple invitations as the validation was added to the invitation model which is created for every single invitation. It's only showing errors for the invitations that where invalid and sends the invitation for the valid once.

**Comment by farhatahmad** [comment]
Hi,

To help us better test and review community PRs, we have now implemented a **mandatory** PR template. We would really appreciate it if you were to update the description of this PR to match the template below. 

For more information, please see: https://github.com/bigbluebutton/greenlight#source-code--contributing

The template must be in the following format (it is automatically applied to all new PRs):
```
<!--- 
IMPORTANT
This template is mandatory for all Pull Requests.
Please follow the template to ensure your Pull Request is reviewed.
-->

<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Testing Steps
<!--- Please describe in detail how to test your changes. -->

## Screenshots (if appropriate):
<!--- Please include screenshots of ALL visual changes. -->

```

**Comment by farhatahmad** [comment]
This MR is missing the template. If you would like this merged, please open a new MR and follow the template provided

**Pull request closed without merging**
