### PR TITLE
Dutch translation: 'Aanmelden' was used for both Sign-in and Sign-up. I fixed this.

### PR DESCRIPTION
**Pull request by jeroenpraat**
To avoid this confusion, I changed it to Inloggen (Sign-in) and Registreren (Sign-up)

In below screenshot you see why I did this change (top right corner).
image

### CODE REVIEW

**Comment by farhatahmad** [comment]
Hi @jeroenpraat ,

Thank you for taking the time to update theses translations.

We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/

**Comment by jeroenpraat** [comment]
@farhatahmad Thank you. I couldn't find the link to Transifex. Only a description how to merge the Transifex changes back into the repo. I surely hope someone can do that, after I changed the required strings.

**Comment by farhatahmad** [comment]
@jeroenpraat Transifex does it automatically if all translations are completed. If there are any empty/untranslated strings, you'll need to translate them for the PR to be created

**Comment by jeroenpraat** [comment]
@farhatahmad I requested membership of the Greenlight team, but I'm still not approved afaik.

**Comment by jeroenpraat** [comment]
@farhatahmad How long does it take that the new translation is auto-merged?

**Comment by farhatahmad** [comment]
Should be created later today, but won't but won't display on your server until we release a new version and you update. 

For the time being, you can either make the changes directly to your docker image and once the update is out it'll override them

```
docker run -it bigbluebutton/greenlight:v2 bash
``` 
Then edit the same file you made in this PR, restart Greenlight and your changes should appear

**Pull request closed without merging**
