### PR TITLE
Ldap authentication CSS customization

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
This PR has the intention to be able to customize the current LDAP page, which comes with the default CSS by the Omniauth and Omniauth-Ldap gem.

### CODE REVIEW

**Comment by rafaeelaudibert** [comment]
For demonstration purposes, this is the old LDAP view login modal:
Old LDAP

And this is the new LDAP authentication page
New LDAP

For comparison purposes, this is the default login modal
Default modal

**Comment by jfederico** [comment]
My big concern with this one is that we are bringing the view to the initializer. If there is no way to style the UI from the view or extend the gem, it may be cleaner to add the gem as a library and apply the changes to the UI there.
The gem is not updated anyways, we are looking into using a fork or forking ourselves.

**Comment by rafaeelaudibert** [comment]
The biggest problem on this is that I needed to extend **2** gems to make this work. I really think that using a maintained fork is a better option than this, but it would work as a MonkeyPatch while the 'use fork/create fork' problem is not solved/decided.

**Comment by jfederico** [comment]
There is a new way for customizing the view through the template instead of breaking the MVC.
Closing this PR

**Pull request closed without merging**
