### PR TITLE
Implemented require authentication room setting

### PR DESCRIPTION
**Pull request by farhatahmad**
## Description

Implemented the `Require Authentication` as a room setting. At the moment, the user will be redirected to the home page if they are not signed in with a toast message

TODO:
- Implement `return_to` functionality so that a user returns to the signed in room after signing in

## Testing Steps

- Enable the setting 
- Copy join url and paste into incognito window
- Ensure you are redirected to home page with an error
- Sign into incognito window
- Repeat and ensure you are not redirected and are able to join

### CODE REVIEW

**Comment by scouillard** [comment]
I get a toast error when changing the `Require users to be signed in before joining` field in admin/room config.
Not sure from the logs what the problem is.

**Comment by hadicheaito1** [comment]
> I get a toast error when changing the `Require users to be signed in before joining` field in admin/room config. Not sure from the logs what the problem is.
> 
> image

Same

**Comment by farhatahmad** [comment]
My bad - forgot to mention you have to drop your DB because of the changed migration

**Comment by scouillard** [comment]
Trying to join the Meeting if you are already logged in doesn't work.
image

**Comment by farhatahmad** [comment]
@scouillard good catch - fixed now

**Review by scouillard — APPROVED** [review]

**Pull request merged**
