### PR TITLE
Desgin for Manage Users Tabs

### LINKED ISSUE #943: The user filter and invite components are too close
Currently when I want to invite a user, I write his email in the search field and hit the `Invite User` button. Then I remember that those components are for two different actions.

It would be nice to rethink the way they are being displayed and make them distinct.

image

### PR DESCRIPTION
**Pull request by mrkeksi**
Hope this closes #943

with invite:
image

without
image

### CODE REVIEW

**Comment by farhatahmad** [comment]
Thanks @mrkeksi. Screenshots look good. Going to pull this locally and try it out and if everything works, get it done as part of 2.7

**Comment by mrkeksi** [comment]
If you filter for rolls you just don't have the invite button anymore. But I think that's acceptable, right?
also i'm thinking if the button should be round. but if i change it then you see the continuous line.

**Comment by mabras** [comment]
@farhatahmad @mrkeksi 
Maybe it is off-topic, but I want to know your input on this. Do Think that `menu_buttons` (left column) should be a subnav of tabs? The right column do not have enough space for its content.

**Comment by mrkeksi** [comment]
You mean with all those tables that seem so tight? Unfortunately, I can't think of a better way to do this if this menu is expanded with more submenus.
I am already thinking about tile instead of table layout.

**Comment by mabras** [comment]
I mean the left column (Users, Rooms, Recording, Roles...) should be a horizontal subnav/tabs. Maybe like [this](https://getbootstrap.com/docs/4.0/components/navs/#horizontal-alignment) or [this](https://getbootstrap.com/docs/4.0/components/navs/#tabs) The subnav will be a 12-col row then the content of it in 12-col row. This will give the content more space.

**Comment by mrkeksi** [comment]
I got what you wanted.  But look at this picture.  With so many menu items it just looks weird.  I could then imagine a button to fold the menu like in bbb top left. 
https://cdn.tutsplus.com/webdesign/uploads/legacy/tuts/375_responsive_menu/img/step3.png

**Pull request merged**
