### PR TITLE
use email input for sign in

### PR DESCRIPTION
**Pull request by sualko**
This is specially useful on mobile devices.﻿

### CODE REVIEW

**Comment by mrkeksi** [comment]
Also here: https://github.com/bigbluebutton/greenlight/blob/8f454cad0ece0a14c678bf0ecc1c6dddff2b873a/app/views/shared/modals/_invite_user_modal.html.erb#L30

https://github.com/bigbluebutton/greenlight/blob/8f454cad0ece0a14c678bf0ecc1c6dddff2b873a/app/views/users/components/_account.html.erb#L30

This cannot be implemented in the Invite Participant field, otherwise it would not be possible to invite multiple participants (separated by commas).

**Comment by sualko** [comment]
Is there a reason why this small pr is not merged?

**Comment by lkiesow** [comment]
@sualko, there seems to be a problem that  @mrkeksi pointed out in the comment above yours, doesn't it?

**Comment by sualko** [comment]
> there seems to be a problem that @mrkeksi pointed out in the comment above yours, doesn't it?

It's no problem, it's an addition. I'm happy to add it, but if there is no willingness to merge this, I don't know why I should commit my time. If this change is required that my pr is merged, I'm happy to do it.

**Comment by farhatahmad** [comment]
@sualko There is. Having trouble working my way through issues, reviewing PRs and doing development. If you can get those extra fields added, then I can get it into the next version

**Comment by sualko** [comment]
Done. Feel free to squash.

**Pull request merged**
