### PR TITLE
[LINT] exigenses in FR translation is printed exigenCes

### PR DESCRIPTION
**Pull request by thifranc**
## Description
I've renamed 'exigenses' to 'exigences' in FRENCH translation.
The privous word was badly written.

### CODE REVIEW

**Comment by jgribonvald** [comment]
This PR can be closed as fix applied in #3056 from Transiflex

**Comment by thifranc** [comment]
I still can find the ocurrence of the word 'exigenses' in the code from SHA cac7c389e41244fa3917f26063eccb2bffdd7f4c ( latest in the PR you mentionned I reckon ). However, if that's easier, I can check on how to contribute through transiflex and make the changes over there ?

**Comment by jgribonvald** [comment]
I've fixed in the same time on providing missing translation but Transiflex didn't push the change, I'm trying to watch if some change apply them...

**Comment by jgribonvald** [comment]
I would say wait and see, the change is applied on transiflex, but it wasn't pushed

**Comment by thifranc** [comment]
Ok for me, closing this issue :) thks !

**Pull request closed without merging**
