### PR TITLE
Implement hCaptcha as an alternative to Google reCaptcha

### PR DESCRIPTION
**Pull request by marvinschopf**
Hello!

I have added [**hCaptcha**](https://www.hcaptcha.com) in this pull request as an alternative to Google reCaptcha.

The operator of the server can set hCaptcha instead of reCaptcha by setting two additional environment variables. The implementation of Google reCaptcha has of course remained. reCaptcha has priority if both services are configured at the same time.

hCaptcha is a captcha provider which is technologically similar to Google reCaptcha, but is much more privacy-oriented and actually rewards the website operator for embedding captchas. Site operators are rewarded with cryptocurrencies proportionately for each captcha solved. This is a great advantage, especially in light of Google's increasingly aggressive monetisation of reCaptcha.

### CODE REVIEW

**Comment by jfederico** [comment]
@marvinschopf thanks for the PR. but before we even review your proposal, can you rebase and squash the commits to 1

**Comment by marvinschopf** [comment]
Hello @jfederico!

Thank you very much for the answer!

I have rebased the branch and combined all the commits into one.

**Comment by farhatahmad** [comment]
Hi,

To help us better test and review community PRs, we have now implemented a **mandatory** PR template. We would really appreciate it if you were to update the description of this PR to match the template below. 

For more information, please see: https://github.com/bigbluebutton/greenlight#source-code--contributing

The template must be in the following format (it is automatically applied to all new PRs):
```
<!--- 
IMPORTANT
This template is mandatory for all Pull Requests.
Please follow the template to ensure your Pull Request is reviewed.
-->

<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Testing Steps
<!--- Please describe in detail how to test your changes. -->

## Screenshots (if appropriate):
<!--- Please include screenshots of ALL visual changes. -->

```

**Comment by farhatahmad** [comment]
This MR is missing the template. If you would like this merged, please open a new MR and follow the template provided

**Pull request closed without merging**
