### PR TITLE
Configuration of default guest policy and fix guest params

### PR DESCRIPTION
**Pull request by miztaka**
Our company has needs to control guest policy at greenlight side. It also fixes inconsistent guest params.

## Features

* Can configure `default guest policy` to other than "ALWAYS_ACCEPT" (Our company needs "ALWAYS_ACCEPT_AUTH")

## Fix

* Fix `guest` parameter for join url

### CODE REVIEW

**Comment by matjazp** [comment]
Do you already run this PR in your production env?

**Comment by matjazp** [comment]
I've tested this PR and it works. Very useful feature. 👍

**Comment by miztaka** [comment]
@matjazp Thank you for checking my PR. Hope to be merged to next release.

**Comment by farhatahmad** [comment]
Hmm I'm not quite sure I like this implementation. If there are multiple guest policies, we'll probably want a drop down there instead of a switch

**Comment by farhatahmad** [comment]
Hi,

To help us better test and review community PRs, we have now implemented a **mandatory** PR template. We would really appreciate it if you were to update the description of this PR to match the template below. 

For more information, please see: https://github.com/bigbluebutton/greenlight#source-code--contributing

The template must be in the following format (it is automatically applied to all new PRs):
```
<!--- 
IMPORTANT
This template is mandatory for all Pull Requests.
Please follow the template to ensure your Pull Request is reviewed.
-->

<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Testing Steps
<!--- Please describe in detail how to test your changes. -->

## Screenshots (if appropriate):
<!--- Please include screenshots of ALL visual changes. -->

```

**Comment by farhatahmad** [comment]
This MR is missing the template. If you would like this merged, please open a new MR and follow the template provided

**Pull request closed without merging**
