### PR TITLE
Increase Database pool size

### PR DESCRIPTION
**Pull request by symptog**
The required pool size is calculated by `RAILS_MAX_THREADS + #Action
Cable-Workers` (default: `5 + 4 = 9`)
The default pool size of 5 is to low for all required connections.

### CODE REVIEW

**Comment by schrd** [comment]
This should be merged. It fixes the problem of slow requests (which are in fact waiting for a free database connection) with 100% CPU load on ruby process.

**Review by basisbit — APPROVED** [review]
@symptog thank you. We use this config successfully already for months. Should be merged.

**Comment by kaystrobach** [comment]
Works for us as well ™️

**Review by jfederico — APPROVED** [review]

**Comment by jfederico** [comment]
Thanks @symptog

**Pull request merged**
