### PR TITLE
feat: Defining a custom default presentation on BBB server

### PR DESCRIPTION
**Pull request by jgribonvald**
Setting from a site configuration the default presentation URL

## Description

This permit to define at the site configuration a default presentation page when launching a new room on the bbb server. 
It permits to override the default presentation of BBB server. 
This default presentation won't override the user pre-loaded presentation.

## Screenshots (if appropriate):

screenshot

### CODE REVIEW

**Comment by jgribonvald** [comment]
Mhh I think that the test are not passing as the @Settings isn't init in test mode, How can I do that ? Or do you see an other way ?
Thansk for your help.

Else I remove the tests as I'm sure this is working

**Comment by jgribonvald** [comment]
Test are passing now !

**Comment by farhatahmad** [comment]
Hi,

To help us better test and review community PRs, we have now implemented a **mandatory** PR template. We would really appreciate it if you were to update the description of this PR to match the template below. 

For more information, please see: https://github.com/bigbluebutton/greenlight#source-code--contributing

The template must be in the following format (it is automatically applied to all new PRs):
```
<!--- 
IMPORTANT
This template is mandatory for all Pull Requests.
Please follow the template to ensure your Pull Request is reviewed.
-->

<!--- Provide a general summary of your changes in the Title above -->

## Description
<!--- Describe your changes in detail -->

## Testing Steps
<!--- Please describe in detail how to test your changes. -->

## Screenshots (if appropriate):
<!--- Please include screenshots of ALL visual changes. -->

```

**Comment by farhatahmad** [comment]
Thank you for applying the changes to the description. If I'm understanding the code correctly, it only allows you to specify a presentation URL but does not allow you to upload a file? If so, I don't believe this method will work. Admins should be able to upload a file to use as the default presentation to keep the actions consistent

**Comment by jgribonvald** [comment]
@farhatahmad Ok I see, in my case (several greenlight in LB) it's better to have a presentation available from an url. Else as the feature use the pre-upload feature, it won't be too much difficult to use both. I will update the PR for that. Just let me some time we are deploying 200 BBB.

**Comment by jgribonvald** [comment]
@farhatahmad I'm not really familiar to RoR and have problems to find a good way to upload files. On an other part, admins have to set an URL on previous options, so if they can provide a custom term or policy URL, they can provide a default file URL...
I will try to continue but how do you see that ? should also must provide a different option on settings.rb ? After I'm trying to upload and use the generated url to save it in the same input.

**Comment by farhatahmad** [comment]
Hmm on second thought, I don't think its possible to make this an actual file upload - atleast not with the way the settings currently work. Let me spend some time thinking about this and I'll make a decision

**Comment by jgribonvald** [comment]
@farhatahmad any news ?

Thanks

**Review by farhatahmad — APPROVED** [review]

**Comment by farhatahmad** [comment]
Can you do a rebase on this please?

**Comment by jgribonvald** [comment]
@farhatahmad rebase done !

**Comment by farhatahmad** [comment]
Needs another rebase :( Or set the `Allow maintainers to edit` setting so that I can

**Comment by jgribonvald** [comment]
@farhatahmad rebase done again !

The `Allow maintainers to edit` doesn't appear on PR already done (before the option activated ?), else I need to recreate it, but we will loose all the talk...

**Pull request closed without merging**
