### PR TITLE
Hide recording menu and recording list when it is disabled

### PR DESCRIPTION
**Pull request by miztaka**
This is PR for https://github.com/bigbluebutton/greenlight/issues/1934.

### CODE REVIEW

**Comment by mrkeksi** [comment]
https://github.com/bigbluebutton/greenlight/blob/50c2070188a6f731af5d4930b59e90e54c77d703/app/views/rooms/components/_room_event.html.erb#L44

**Comment by farhatahmad** [comment]
@miztaka Thanks for the PR Mitsu. @mrkeksi is correct, there is one more place that recordings could appear as well

**Comment by miztaka** [comment]
@farhatahmad @mrkeksi Thank you for checking this. I changed _room_event.html.erb as well.

**Comment by miztaka** [comment]
Thanks you for checking this @farhatahmad !

**Comment by mrkeksi** [comment]
@miztaka Nothing changes for me at all? Does it just not work for me?

**Comment by farhatahmad** [comment]
Did you set "allow room to be recorded" to `disabled` in your Room Configuration?

**Comment by mrkeksi** [comment]
Of course, I switched, saved and switched again. Nothing happens (my patch-3 branch).

Also, I wonder, if it's room specific, why should "All records" be removed from the header?

**Comment by miztaka** [comment]
hi @mrkeksi , this works when you disable recording in admin console, not room specific. cheers.

**Comment by farhatahmad** [comment]
Reverting this in #1959. Noticed some slightly weird behaviour, but I don't want to delay 2.7 before I can fix it. I'll take a crack at this again in 2.7.1

**Comment by miztaka** [comment]
What problem did you find? I'm happy to fix it.

**Pull request merged**
