### PR TITLE
Update to Ruby 2.7

### PR DESCRIPTION
**Pull request by lkiesow**
The currently used Ruby 2.5 is pretty old and is nearing its end of
life [1]. This patch updates the used Ruby version to the current
stable version.

[1] https://www.ruby-lang.org/en/downloads/branches/

### CODE REVIEW

**Comment by farhatahmad** [comment]
This should probably change the the version in the `.ruby-version` file aswell

**Comment by lkiesow** [comment]
Done.

**Comment by mabras** [comment]
Maybe you should alson edit `.gitlab-ci.yml` to use the new version.

**Comment by lkiesow** [comment]
I deliberately did not change any CI things since this technically does not change the minimum Ruby version required to run Greenlight. Also, `.gitlab-ci.yml` doesn't actually seem to be used any longer. But then, you could have made the argument for `.travis.yml`

**Comment by mabras** [comment]
@farhatahmad, We have been useing `2.7` With GL for month now. It is error free. How about we include this in `2.7.13`?

**Pull request merged**
